development:
  secret_key_base: bc56a7486f0b367c3dcf9eb2b23e626f213f050f6ea3273822e7757b5c91c1bace2d6d0fb3c3513f66cc5315eab9ea3a45c1d808f984f329970ec5115c75aeb1
  facebook_app_id: 190102614732546
  facebook_app_secret: 04f699e21697db649c77bb1cab37bafe

  twitter_app_id: x70FYQUNVAUXMnwcMGbhJ2DM4
  twitter_app_secret: 2yfQtnRZ81uRGC3k9It3n56DvQDL6n5opYKnq3TJie4A39m2MP
test:
  secret_key_base: ee48a2622240ac00edc8e58243f4c22c101782f93db0d4db64cffc5d4378c5be802b86fdc9c5472aef3b9aca4fbfa2d18cc42ce89e501db3b1fd256bf5f94a86

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
